x-icloudpd-common: &icloudpd-common
  image: icloudpd/icloudpd:latest@sha256:af2bf40cb2c1d42051793b4c3c04c825950697d7fedcd12bd8455d6952395801
  user: 1026:100
  environment:
    TZ: America/Santiago
  volumes:
    - /volume1/docker/icloud2/config:/config
    - /volume1/homes/SMaluk/Photos/icloud:/data
  networks:
    - icloudpd_bridge

services:
  icloudpd:
    container_name: icloudpd
    ports:
      - '8085:8080'
    command: >-
      icloudpd --directory /data/PrimarySync --username ${APPLE_USERNAME} --cookie-directory /config/cookies --library "PrimarySync" --folder-structure none --file-match-policy name-size-dedup-with-suffix --live-photo-mov-filename-policy suffix --align-raw as-is --size original --live-photo-size original --auto-delete --watch-with-interval 3600 --password-provider webui --mfa-provider webui --no-progress-bar
    restart: unless-stopped
    <<: *icloudpd-common
    hostname: icloudpd

  icloudpd-auth:
    container_name: icloudpd-auth
    ports:
      - '8086:8080'
    command: >-
      icloudpd --directory /data --username ${APPLE_USERNAME} --cookie-directory /config/cookies --auth-only --password-provider webui --mfa-provider webui --no-progress-bar
    restart: "no"
    <<: *icloudpd-common
    hostname: icloudpd-auth
    profiles:
      - auth

  icloudpd-shared:
    container_name: icloudpd-shared
    command: >-
      icloudpd --directory /data/SharedSync-11FA8566-11D0-4EF2-9A8B-352341D031CE --username ${APPLE_USERNAME} --cookie-directory /config/cookies --library "SharedSync-11FA8566-11D0-4EF2-9A8B-352341D031CE" --folder-structure none --file-match-policy name-size-dedup-with-suffix --live-photo-mov-filename-policy suffix --align-raw as-is --size original --live-photo-size original --auto-delete --watch-with-interval 3600 --password-provider webui --mfa-provider webui --no-progress-bar
    restart: unless-stopped
    <<: *icloudpd-common
    hostname: icloudpd-shared

networks:
  icloudpd_bridge:
    driver: bridge
