x-icloudpd-common: &icloudpd-common
  image: icloudpd/icloudpd:latest@sha256:eb5fad6a58dc77ffa8c87d47078df28269959726eb58ed23502d27f6c6976c94
  user: 1026:100
  environment:
    TZ: America/Santiago
  volumes:
    - /volume1/docker/icloud2/config:/config
    - /volume1/homes/SMaluk/Photos/icloud:/data
  networks:
    - icloudpd_bridge

services:
  icloudpd:
    <<: *icloudpd-common
    container_name: icloudpd
    hostname: icloudpd
    command: >-
      icloudpd
      --directory /data/PrimarySync
      --username ${APPLE_USERNAME}
      --cookie-directory /config/cookies
      --library "PrimarySync"
      --folder-structure none
      --file-match-policy name-size-dedup-with-suffix
      --live-photo-mov-filename-policy suffix
      --align-raw as-is
      --size original
      --live-photo-size original
      --auto-delete
      --watch-with-interval 3600
      --password-provider webui
      --mfa-provider webui
      --no-progress-bar
    ports:
      - 8085:8080
    restart: unless-stopped

  icloudpd-shared:
    <<: *icloudpd-common
    container_name: icloudpd-shared
    hostname: icloudpd-shared
    command: >-
      icloudpd
      --directory /data/SharedSync-11FA8566-11D0-4EF2-9A8B-352341D031CE
      --username ${APPLE_USERNAME}
      --cookie-directory /config/cookies
      --library "SharedSync-11FA8566-11D0-4EF2-9A8B-352341D031CE"
      --folder-structure none
      --file-match-policy name-size-dedup-with-suffix
      --live-photo-mov-filename-policy suffix
      --align-raw as-is
      --size original
      --live-photo-size original
      --auto-delete
      --watch-with-interval 3600
      --password-provider webui
      --mfa-provider webui
      --no-progress-bar
    restart: unless-stopped

  icloudpd-auth:
    <<: *icloudpd-common
    container_name: icloudpd-auth
    hostname: icloudpd-auth
    profiles:
      - auth
    command: >-
      icloudpd
      --directory /data
      --username ${APPLE_USERNAME}
      --cookie-directory /config/cookies
      --auth-only
      --password-provider webui
      --mfa-provider webui
      --no-progress-bar
    ports:
      - 8086:8080
    restart: "no"

networks:
  icloudpd_bridge:
    driver: bridge
