services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.52.4
    container_name: changedetection
    volumes:
      - /volume1/docker/changedetection:/datastore
    environment:
      - TZ=America/Santiago
      - PGID=100
      - PUID=1026
    ports:
      - '5900:5000'
    restart: always
