services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.55.7@sha256:736331d2787f94d3201b64aa641e090f67e28577ba505bd7ba5d7c1841e1e0ca
    container_name: changedetection
    volumes:
      - /volume1/docker/changedetection:/datastore
    environment:
      - TZ=America/Santiago
      - PGID=100
      - PUID=1026
    ports:
      - '5900:5000'
    restart: always
