services:
  changedetection:
    image: dgtlmoon/changedetection.io:0.54.7@sha256:b632a9fb6be702fb859e02cd5cac5de7a7466ce1e97f5f5347a1d012c0720108
    container_name: changedetection
    volumes:
      - /volume1/docker/changedetection:/datastore
    environment:
      - TZ=America/Santiago
      - PGID=100
      - PUID=1026
    ports:
      - '5900:5000'
    restart: always
