services:
  sonarr:
    image: linuxserver/sonarr:4.0.17
    container_name: sonarr
    volumes:
      - /volume1/downloads:/downloads
      - /volume1/homes/plex/TV Shows:/movies
      - /volume1/docker/sonarr/config:/config
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '8989:8989'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8989/ || exit 1
    security_opt:
      - no-new-privileges:true
