services:
  tautulli:
    image: tautulli/tautulli:v2.18.2@sha256:1b5875fe3193d450a62e7b438eb6701195c841f14f3dcb962e545eda42d3696f
    container_name: tautulli
    volumes:
      - /volume1/docker/tautulli:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Santiago
    ports:
      - '8181:8181'
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      homelab.hostname: 'tautulli'
      traefik.http.routers.tautulli.middlewares: 'hsts@file'
      traefik.http.services.tautulli.loadbalancer.server.port: '8181'

networks:
  default:
  proxy:
    external: true
    name: homelab-proxy
