services:
  tautulli:
    image: tautulli/tautulli:v2.17.0@sha256:9c73937390116e6875970f4c816ddfa9d905cc88f76f2ddbf4eaca2ea2715006
    container_name: tautulli
    volumes:
      - /volume1/docker/tautulli:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Santiago
    ports:
      - '8181:8181'
    restart: unless-stopped
