services:
  tautulli:
    image: tautulli/tautulli:v2.18.0@sha256:f8b4a2693198b67497ecf4a35367eb7b40e91a7b225551b61587df164f6a99b1
    container_name: tautulli
    volumes:
      - /volume1/docker/tautulli:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Santiago
    ports:
      - '8181:8181'
    restart: unless-stopped
