services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.0.4
    container_name: qbittorrent
    volumes:
      - /volume1/docker/qbittorrent/config:/config:rw
      - /volume1/downloads:/downloads:rw
    environment:
      - WEBUI_PORT=9865
      - PUID=1026
      - PGID=100
      - TZ=America/Santiago
    ports:
      - '9865:9865'
      - '27581:27581'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:9865/ || exit 1

    security_opt:
      - no-new-privileges:true
    # network_mode: "service:gluetun"
    tty: true
