services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual-server
    ports:
      - 5007:5007
    environment:
      - ACTUAL_PORT=5007
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=50

    volumes:
      - /volume1/docker/actual-budget/actual-data:/data:rw
    restart: unless-stopped
