services:
  prowlarr:
    image: linuxserver/prowlarr:2.3.5@sha256:c5de2a8758a05594319263e7691c1dce56899442ed1720d6eca216c0958f4caf
    container_name: prowlarr
    volumes:
      - /volume1/docker/prowlarr:/config:rw
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '9696:9696'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:9696/ || exit 1
    security_opt:
      - no-new-privileges:true
