services:
  prowlarr:
    image: linuxserver/prowlarr:2.4.0@sha256:3e9bd62ca90c97c5df75b7012e10a29f6926e62807deeddc1dc89e6e2fd141e1
    container_name: prowlarr
    volumes:
      - /volume1/docker/prowlarr:/config:rw
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '9696:9696'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:9696/ || exit 1
    security_opt:
      - no-new-privileges:true
