services:
  tdarr:
    image: haveagitgat/tdarr:2.79.01@sha256:d32377acacf653c351a115e25e46a59530d77551feb4531b6928e5dbd49df970
    container_name: tdarr

    volumes:
      - /volume1/docker/tdarr/server:/app/server
      - /volume1/docker/tdarr/configs:/app/configs
      - /volume1/docker/tdarr/logs:/app/logs
      - /volume1/homes/plex:/home/Tdarr/media
      - /volume1/docker/tdarr/temp:/temp
    environment:
      - TZ=America/Santiago
      - PUID=1026
      - PGID=100
      - serverIP=${TDARR_SERVER_IP}
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
    ports:
      - '8265:8265'
      - '8266:8266'
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8265/ || exit 1
    hostname: tdarr
    security_opt:
      - no-new-privileges:true
