services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:2.63.01@sha256:6d3522f8bfea78614348b6be20e91d1d3e11e045c287b21be95dba55f49e242e
    container_name: tdarr

    volumes:
      - /volume1/docker/tdarr/server:/app/server
      - /volume1/docker/tdarr/configs:/app/configs
      - /volume1/docker/tdarr/logs:/app/logs
      - /volume1/homes/plex:/home/Tdarr/media
      - /volume1/docker/tdarr/temp:/temp
    environment:
      - TZ=America/Santiago
      - PUID=1026
      - PGID=100
      - serverIP=192.168.1.12
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
    ports:
      - '8265:8265'
      - '8266:8266'
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8265/ || exit 1
    hostname: tdarr
    security_opt:
      - no-new-privileges:true
