services:
  tdarr:
    image: haveagitgat/tdarr:2.82.01@sha256:776896d7b0869f256739bad500bc566ef68ca23a53c9fc06eccbe2af1eb1c7f5
    container_name: tdarr

    volumes:
      - /volume1/docker/tdarr/server:/app/server
      - /volume1/docker/tdarr/configs:/app/configs
      - /volume1/docker/tdarr/logs:/app/logs
      - /volume1/homes/plex:/home/Tdarr/media
      - /volume1/docker/tdarr/temp:/temp
    environment:
      - TZ=America/Santiago
      - PUID=1026
      - PGID=100
      - serverIP=${TDARR_SERVER_IP}
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
    ports:
      - '8265:8265'
      - '8266:8266'
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8265/ || exit 1
    hostname: tdarr
    security_opt:
      - no-new-privileges:true
