services:
  plex:
    image: plexinc/pms-docker:1.43.2.10687-563d026ea@sha256:c37106c57fed7a6624f5dee5a3ce460ff011f09a2aa7f4ee9e8dbbd08ae1b87e
    container_name: plex
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/homes/plex/TV Shows:/tv
      - /volume1/homes/plex/Movies:/movies
      - /volume1/homes/plex/Music:/music
      - /volume1/homes/plex/Rugby:/rugby
    environment:
      - PLEX_UID=1026
      - PLEX_GID=100
      - TZ=America/Santiago
      - VERSION=public
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
