services:
  plex:
    image: plexinc/pms-docker:1.42.2.10156-f737b826c@sha256:9c03c26b9479ba9a09935f3367459bfdc8d21545f42ed2a13258983c5be1b252
    container_name: plex
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/homes/plex/TV Shows:/tv
      - /volume1/homes/plex/Movies:/movies
      - /volume1/homes/plex/Music:/music
      - /volume1/homes/plex/Rugby:/rugby
    environment:
      - PLEX_UID=1026
      - PLEX_GID=100
      - TZ=America/Santiago
      - VERSION=public
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
