services:
  plex:
    image: plexinc/pms-docker:1.43.1.10611-1e34174b1@sha256:8b5bcdf7b506fe051aa1a0a0d464efdb3ad8c0fb1f8a4dfb27a8c489b609920c
    container_name: plex
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/homes/plex/TV Shows:/tv
      - /volume1/homes/plex/Movies:/movies
      - /volume1/homes/plex/Music:/music
      - /volume1/homes/plex/Rugby:/rugby
    environment:
      - PLEX_UID=1026
      - PLEX_GID=100
      - TZ=America/Santiago
      - VERSION=public
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
