services:
  pihole:
    image: pihole/pihole:2026.06.0@sha256:8ea95136e7c8c15b42d88eadf1a3875421aa1be30ad39e50f661188cc986fb27
    container_name: pihole
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
    environment:
      FTLCONF_webserver_api_password: ${PIHOLE_WEB_PASSWORD}
      FTLCONF_webserver_port: 8080
      FTLCONF_dns_listeningMode: all
      TZ: America/Santiago
      DNSMASQ_USER: pihole #or root NOT recommended to use root.
      PIHOLE_UID: 1026
      PIHOLE_GID: 100
    network_mode: host
    restart: on-failure:5
    cap_add:
      - SYS_TIME
      - SYS_NICE
    security_opt:
      - no-new-privileges:false
