services:
  pihole:
    image: pihole/pihole:2026.05.0@sha256:70a9c11171ded2eee735d88c127996da209284a329d50f5ae59c06b861d401b3
    container_name: pihole
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
    environment:
      FTLCONF_webserver_api_password: admin
      FTLCONF_webserver_port: 8080
      FTLCONF_dns_listeningMode: all
      TZ: America/Santiago
      DNSMASQ_USER: pihole #or root NOT recommended to use root.
      PIHOLE_UID: 1026
      PIHOLE_GID: 100
    network_mode: host
    restart: on-failure:5
    cap_add:
      - SYS_TIME
      - SYS_NICE
    security_opt:
      - no-new-privileges:false
