services:
  radarr:
    image: linuxserver/radarr:6.1.1@sha256:659e5f20500948b1491f31dd85c6f99a43508ce3e46595793e1e15aa955bf6d7
    container_name: radarr
    volumes:
      - /volume1/downloads:/downloads
      - /volume1/homes/plex/Movies:/movies
      - /volume1/docker/radarr/config:/config
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '7878:7878'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:7878/ || exit 1
    security_opt:
      - no-new-privileges:true
