services:
  radarr:
    image: ghcr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    volumes:
      - /volume1/downloads:/downloads
      - /volume1/homes/plex/Movies:/movies
      - /volume1/docker/radarr/config:/config
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '7878:7878'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:7878/ || exit 1
    security_opt:
      - no-new-privileges:true
