services:
  home-assistant:
    image: linuxserver/homeassistant:2026.4.1@sha256:30ec0e89ccd6b693fbbf43e606a6f2500c0e5e308598a7811c3301f82d59e54e
    container_name: home-assistant
    volumes:
      - /volume1/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: 1026
      PGID: 100
      TZ: America/Santiago
    network_mode: host
    restart: unless-stopped
    privileged: true
