services:
  home-assistant:
    image: linuxserver/homeassistant:2026.6.3@sha256:af007f8c7115eec85f6cc63cab9946faefde7139557faa868076bbb455d0085f
    container_name: home-assistant
    volumes:
      - /volume1/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: 1026
      PGID: 100
      TZ: America/Santiago
    network_mode: host
    restart: unless-stopped
    privileged: true
