services:
  home-assistant:
    image: linuxserver/homeassistant:2026.6.4@sha256:27b5661081d676755bf2851aca9ad9a78ca0bb1fafcb138280524b28e8d06ffd
    container_name: home-assistant
    volumes:
      - /volume1/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: 1026
      PGID: 100
      TZ: America/Santiago
    network_mode: host
    restart: unless-stopped
    privileged: true
