services:
  whatsupdocker:
    image: getwud/wud:8.1.1
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_TRIGGER_NTFY_PRIVATE_TOPIC=wud-iAn8Pf5T7put02tt
      - WUD_TRIGGER_NTFY_PRIVATE_URL=https://ntfy.malukzedan.synology.me
    ports:
      - '3000:3000'
