services:
  backend:
    image: infisical/infisical:v0.159.4@sha256:e4172c62f45b960d6d4754a508c24057da0c81d5a501a3327d3b525b526f3f79
    container_name: infisical-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - '8002:8080'
    networks:
      - infisical
    restart: unless-stopped
    pull_policy: always

  db:
    image: postgres:14-alpine@sha256:64ce25a0bb68e598edc3944f2f58f39d1e8641755baa4ba5f7ddfa142ed85c63
    container_name: infisical-db
    volumes:
      - /volume1/docker/infisical/pg_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - infisical
    restart: always
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis@sha256:009cc37796fbdbe1b631b4cc0582bed167e5e403ed8bcd06f77eb6cb5aeb6f93
    container_name: infisical-dev-redis
    volumes:
      - /volume1/docker/infisical/redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file: .env
    ports:
      - '6380:6379'
    networks:
      - infisical
    restart: always

networks:
  infisical:

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
