services:
  backend:
    image: infisical/infisical:v0.165.16@sha256:6b911e3938ac2ff385a782df59ce9272799be7976d26dc5667266a2aecac4116
    container_name: infisical-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - '8002:8080'
    networks:
      - infisical
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      homelab.hostname: 'infisical'
      traefik.http.routers.infisical.middlewares: 'hsts@file'
      traefik.http.services.infisical.loadbalancer.server.port: '8080'
    pull_policy: always

  db:
    image: postgres:14-alpine@sha256:64ce25a0bb68e598edc3944f2f58f39d1e8641755baa4ba5f7ddfa142ed85c63
    container_name: infisical-db
    volumes:
      - /volume1/docker/infisical/pg_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - infisical
    restart: always
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis@sha256:8aee6591ee8c2b26e9e01ad4913fbc804ea6b79a9bc675ee1824d80ea5dd9856
    container_name: infisical-dev-redis
    volumes:
      - /volume1/docker/infisical/redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file: .env
    ports:
      - '6380:6379'
    networks:
      - infisical
    restart: always

networks:
  infisical:
  proxy:
    external: true
    name: homelab-proxy

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
