services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    container_name: jellyfin
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/docker/jellyfin/cache:/cache
      - /volume1/homes/plex/TV Shows:/tv
      - type: bind
        source: /volume1/homes/plex
        target: /media
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL}
    ports:
      - '7359:7359/udp'
      - '8096:8096/tcp'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'
    user: 1026:100
