services:
  watchstate:
    image: arabcoders/watchstate:v1.0.8@sha256:47143eaa49135dfcdb3bbc351046c81ec1cfa7bf3c6a0141b08ed7b9c32b03d7
    container_name: watchstate
    volumes:
      - /volume1/docker/watchstate:/config:rw
    ports:
      - '9090:8080'
    restart: unless-stopped
    user: 1026:100
    command: ["sleep", "infinity"]