services:
  bazarr:
    image: linuxserver/bazarr:1.6.0@sha256:4c30dc0bb9a5d223075e7f5d12c77bd293c4b460f86d696dbe64763104c1e88c
    container_name: bazarr
    volumes:
      - /volume1/docker/bazarr:/config:rw
      - /volume1/homes/plex:/media
    environment:
      - TZ=America/Santiago
      - PGID=100
      - PUID=1026
    ports:
      - '6767:6767'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:6767/ || exit 1
    security_opt:
      - no-new-privileges:false
