services:
  minecraft:
    image: marctv/minecraft-papermc-server:26.1.2@sha256:09b944fd03d329f55d12546a170b7254f999fed64f0f5c7258f7eb63353594c5
    container_name: "minecraft-server-paper"
    volumes:
      - /volume1/docker/minecraft/data:/data
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
    ports:
      - '25565:25565'
    stdin_open: true
    tty: true
