services:
  minecraft:
    image: marctv/minecraft-papermc-server:26.1.2@sha256:732d0aa849cc6741e74a725165ca1cb0891105582d7b587533876e30ffc43aad
    container_name: "minecraft-server-paper"
    volumes:
      - /volume1/docker/minecraft/data:/data
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
    ports:
      - '25565:25565'
    stdin_open: true
    tty: true
