services:
  lidarr:
    image: linuxserver/lidarr:2.14.5
    container_name: lidarr
    volumes:
      - /volume1/homes/plex/Music:/music
      - /volume1/downloads:/downloads
      - /volume1/docker/lidarr/config:/config
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '8686:8686'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8686/ || exit 1
    security_opt:
      - no-new-privileges:true
