services:
  db:
    image: postgres:17-alpine@sha256:c7526c0f6c3f30260a563d7bcf8ad778effac59a44f8ffa86678c35418338609
    container_name: lidarr-db
    volumes:
      - /volume1/docker/lidarr/db:/var/lib/postgresql/data
      - /volume1/docker/lidarr/multiple-databases.sh:/docker-entrypoint-initdb.d/10-multiple-databases.sh:ro
    environment:
      POSTGRES_USER: lidarr
      POSTGRES_PASSWORD: lidarr
      POSTGRES_DB: lidarr-main
      POSTGRES_MULTIPLE_DATABASES: lidarr-log
    ports:
      - '5433:5432'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lidarr -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  lidarr:
    image: linuxserver/lidarr:3.1.0@sha256:e9a275176e8158638395cc8574b02b7695006f70bde48830a09fa6ab5b6775df
    container_name: lidarr
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /volume1/homes/plex/Music:/music
      - /volume1/downloads:/downloads
      - /volume1/docker/lidarr/config:/config
    environment:
      TZ: America/Santiago
      PGID: 100
      PUID: 1026
    ports:
      - '8686:8686'
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8686/ || exit 1
    security_opt:
      - no-new-privileges:true
