services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.2.0@sha256:85d68948704fcadc7438f45c9f2666ef2239b5b84073479e1c5bc4d4d8b6d17c
    container_name: uptime-kuma
    volumes:
      - /volume1/docker/uptime-kuma:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Santiago
    ports:
      - '3444:3001'
    restart: on-failure:5
    cpu_shares: 1024
    hostname: uptimekuma
    mem_limit: 4g
