services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.3@sha256:3e24e96c89efff0e3a4b0698cbdd36c15ad3022371db57166e5588853002ee5c
    container_name: uptime-kuma
    volumes:
      - /volume1/docker/uptime-kuma:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Santiago
    ports:
      - '3444:3001'
    restart: on-failure:5
    cpu_shares: 1024
    hostname: uptimekuma
    mem_limit: 4g
