services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:8.5.3@sha256:e23a0d3dc686e4bbc9eeb655aeb96a2a1352bd2a26297ec77e06ef6f8eb2d5e1
    container_name: jellyplex-watched
    volumes:
      - /volume1/docker/jellyplex-watched:/app/data
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Santiago
    env_file: .env
    restart: unless-stopped
