services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:8.5.2@sha256:dfcd11bda917e281cd11352a7744bcb26d58ed021b0b452b10a1dbe3ce715c18
    container_name: jellyplex-watched
    volumes:
      - /volume1/docker/jellyplex-watched:/app/data
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Santiago
    env_file: .env
    restart: unless-stopped
