services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:v2026.7.0@sha256:873900b6ded729313650c2b82f302978158b434ba53fe110ab2eda271af873eb
    container_name: wizarr
    volumes:
      - /volume1/docker/wizarr:/data
    environment:
      - PUID=1026
      - PGID=100
      - DISABLE_BUILTIN_AUTH=false
      - TZ=America/Santiago
    ports:
      - '5690:5690'
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:5690/ || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
