services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:v2026.9.0@sha256:0627e8e13f0fa76ab3a0348153bdcba5083c9f86745299a81394b8099900758e
    container_name: wizarr
    volumes:
      - /volume1/docker/wizarr:/data
    environment:
      - PUID=1026
      - PGID=100
      - DISABLE_BUILTIN_AUTH=false
      - TZ=America/Santiago
    ports:
      - '5690:5690'
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:5690/ || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
