services:
  maintainerr:
    image: jorenn92/maintainerr:3.8.0@sha256:014fcae5d4cfae96bfb239ebe9368751549e9516947435f4e07520add92cf19e
    container_name: maintainerr
    volumes:
      - /volume1/docker/maintainerr:/opt/data
    environment:
      - TZ=America/Santiago
    ports:
      - '6246:6246'
    restart: unless-stopped
    user: 1026:100
