services:
  maintainerr:
    image: jorenn92/maintainerr:3.11.1@sha256:11fa7153bb4100b92f0b14509dbbd8921097fc6afd0ed7a5babf41a76c78bad4
    container_name: maintainerr
    volumes:
      - /volume1/docker/maintainerr:/opt/data
    environment:
      - TZ=America/Santiago
    ports:
      - '6246:6246'
    restart: unless-stopped
    user: 1026:100
