services:
  maintainerr:
    image: jorenn92/maintainerr:3.16.0@sha256:0829781eb442f93065edda051d4a87f343a1cf05f7ea03635e87306fc786f087
    container_name: maintainerr
    volumes:
      - /volume1/docker/maintainerr:/opt/data
    environment:
      - TZ=America/Santiago
    ports:
      - '6246:6246'
    restart: unless-stopped
    user: 1026:100
